[package]
name = "asdbctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libusb = "0.3.0"
clap = { version = "4.0", features = ["derive"] }
clap-num = "1.0.2"
